name: Test and Pack
on: [push]
jobs:
  test-fpclatest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # We use https://github.com/marketplace/actions/setup-lazarus-environment
      # to setup FPC+Lazarus easily.
      # - uses: gcarreno/setup-lazarus@v3.0.16
      #   with:
      #     lazarus-version: "stable"

      # Use Docker image with CGE prerequisites (FPC, Lazarus, Android tools etc.)
      # See https://hub.docker.com/r/kambi/castle-engine-cloud-builds-tools/ .
      - uses: docker://kambi/castle-engine-cloud-builds-tools:cge-none

      # Set env CASTLE_ENGINE_PATH following
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
      # https://brandur.org/fragments/github-actions-env-vars-in-env-vars
      - name: Set environment
        run: echo "CASTLE_ENGINE_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Build Tools (FPC Stable)
        run: make clean tools
      - name: Build Examples (FPC Stable)
        run: make clean examples
      - name: Build Examples Using Lazarus (FPC / Lazarus Stable)
        run: make clean examples-laz
      - name: Build And Run Auto-Tests (FPC Stable)
        run: make clean tests
      - name: Build Using FpMake (FPC Stable)
        run: make clean test-fpmake
  test-fpc320:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # We use https://github.com/marketplace/actions/setup-lazarus-environment
      # to setup FPC+Lazarus easily.
      # - uses: gcarreno/setup-lazarus@v3.0.16
      #   with:
      #     # latest version with FPC 3.2.0 on https://github.com/marketplace/actions/setup-lazarus-environment
      #     lazarus-version: "2.0.12"

      # Use Docker image with CGE prerequisites (FPC, Lazarus, Android tools etc.)
      # See https://hub.docker.com/r/kambi/castle-engine-cloud-builds-tools/ .
      - uses: docker://kambi/castle-engine-cloud-builds-tools:cge-none

      - name: Set environment
        run: echo "CASTLE_ENGINE_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Build Tools (FPC 3.2.0)
        run: make clean tools
      - name: Build Examples (FPC 3.2.0)
        run: make clean examples
      - name: Build Examples Using Lazarus (FPC 3.2.0 / Lazarus 2.0.12)
        run: make clean examples-laz
      - name: Build And Run Auto-Tests (FPC 3.2.0)
        run: make clean tests
      - name: Build Using FpMake (FPC 3.2.0)
        run: make clean test-fpmake
  pack:
    needs: [test-fpc320, test-fpclatest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: gcarreno/setup-lazarus@v3.0.16
      #   with:
      #     lazarus-version: "stable"

      # Use Docker image with CGE prerequisites (FPC, Lazarus, Android tools etc.)
      # See https://hub.docker.com/r/kambi/castle-engine-cloud-builds-tools/ .
      - uses: docker://kambi/castle-engine-cloud-builds-tools:cge-none

      - name: Set environment
        run: echo "CASTLE_ENGINE_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Remove previous artifacts
        run: rm -f castle-engine*.zip
      - name: Pack
        run: ./tools/internal/pack_release/pack_release.sh
